### ISSUE TITLE
Standardize branch names

### ISSUE THREAD

**Issue by gergopokol** [osrep/Runin#10]
In order to comply with Git standards branches are to be renamed as:
master --> development
release-branch --> master
Prior to doing this, all other branches are to be merged and deleted.
After doing this, repo is to be cloned again to every possible location.

**Comment by olaszsoma** [comment]
Renaming done using the following [lines](https://www.w3docs.com/snippets/git/how-to-rename-git-local-and-remote-branches.html):
git checkout master
git pull
git branch -m master development
git push origin :master development (had to change default branch on Github to development)
git push origin :master
git checkout release-branch
git pull
git branch -m release-branch master
git push origin :release-branch master

Change default branch to master. Clone repos everywhere.
