### ISSUE TITLE
Effective charge calculation might be pointless

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runin#20]
Runin [calculates](https://github.com/osrep/Runin/blob/master/cpo_utils.cpp#L80) effective charge from the ion species present in the plasma (i.e. from the ion and impurity charges). There is a z_eff CPO in coreprof, it might be beneficial to use that instead of calculation, as it will be more likely to be filled.

**Comment by gergopokol** [comment]
The data stored in CPOs is quite redundant, and most often only partially filled. We should require as few data as input as possible. 

We might still check if the Z_eff data in the CPOs is consistent with the impurity content, but this is a general data consistency check, and thus out of the scope of the present project.

**Comment by olaszsoma** [comment]
For self-consistency, the effective charge should be calculated from the impurity and main ion content. Runafluid at the moment takes this value from the coreprof.zeff CPO, but this will change with the 2.0 version, where the new analytical formulas will need impurity content. Runin should keep this calculation and Runafluid will have the same calculation implemented in 2.0 (where the impurity content will be needed anyway.)
