### ISSUE TITLE
Remove workflows folder

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runin#34]
The workflows should be moved to gforge svn repository to the relevant folders (kepler_workflows/trunk/4.10b/runaways or kepler_workflows/trunk/imas/actor_test_workflows/runaways). The version control will be carried out there from now on. After moving the workflows, they should be removed from the git repositories. This issue is similar to the Runafluid [issue #53](https://github.com/osrep/Runafluid/issues/53).

**Comment by gergopokol** [comment]
CPO runaway workflow had already been maintained in the Runafluid repo even before the move, and so all such workflows in the Runin repo are obsolete.

IMAS runaway workflow has been uploaded to /trunk/imas/actor_test_workflows/runaways of KeplerWorkflows: https://gforge6.eufus.eu/gf/project/keplerworkflows/scmsvn/?action=browse&path=%2Ftrunk%2Fimas%2Factor_test_workflows%2Frunaways%2F

--> All workflows can now be removed.

**Comment by gergopokol** [comment]
workflow-remove branch created.

**Comment by olaszsoma** [comment]
Workflows removed, changes merged to development branch. Issue can be closed.
