### ISSUE TITLE
Coulomb logarithm

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runin#4]
The coulomb logarithm calculation in Runin and [Runafluid](https://github.com/gergopokol/Runafluid/commit/32098dc45bc24e2016227bc1c796b1c905da051d) are done using log base 10, whereas the formula used should contain ln, according to Wesson's Tokamaks book. Have to check which is the correct.

**Comment by olaszsoma** [comment]
Wesson's Tokamak uses the same formula as used in the codes, for electron-electron collisions with the difference of having ln of the density and temperature (page 661). Have to find out the reason for using log10 here.

**Comment by olaszsoma** [comment]
It is probably a mistake, have to correct the calculation to natural logarithm.

**Comment by olaszsoma** [comment]
Correction done, have to test before pull request.

**Comment by olaszsoma** [comment]
Runin has been run on IMAS environment without a problem.

**Comment by olaszsoma** [comment]
Test cases file was modified according to the new Coulomb logarithm formula. Have to do the google test for the new values. If passes, we can do a pull request.

**Comment by olaszsoma** [comment]
The test values in the test_phys file modified according to the new excel values. The two separate growth rate cases calculated next to each other in the excel file for future reference. Google test ran successfully.

**Comment by olaszsoma** [comment]
Coulomb logarithm was taken as a constant variable in test_phys.cpp, the test was done with the new script successfully.

**Comment by olaszsoma** [comment]
Merge to master successfully done. propagate through all the branches.

**Comment by olaszsoma** [comment]
Release branch does not contain the Coulomb logarithm fix yet.

**Comment by gergopokol** [comment]
Tested, and can be closed.
