### ISSUE TITLE
New standard directory structure

### ISSUE THREAD

**Issue by gergopokol** [osrep/Runin#43]
There is a directory structure standard for cpp codes. This should be adapted, while still respecting the EU-IM conventions.

This should first be discussed.
Then implemented just after the release of 1.8.2.

**Comment by gergopokol** [comment]
Git submodules seem to work fine. It should be discussed if we would like to move the physics into a separate repository.

**Comment by micskeiz** [comment]
See this guide which recommends a project structure for CMake-based projects (it is also a good guide for CMake):
- https://cliutils.gitlab.io/modern-cmake/chapters/basics/structure.html

See this project from our lab, which also uses similar conventions:
- https://github.com/ftsrg/gazer

**Comment by olaszsoma** [comment]
This issue can be closed.
