### ISSUE TITLE
Sonarcloud implementation for static testing

### ISSUE THREAD

**Issue by pordaniel01** [osrep/Runin#46]
https://sonarcloud.io/documentation

This static testing enviroment was proposed by @micskeiz

**Comment by micskeiz** [comment]
Example for C++ project + Travis + SonarCloud:
https://github.com/SonarSource/sonarcloud_example_cpp-cmake-linux-travis

This is with CMake instead of make, but only the .travis.yml needs to updated accordingly.

**Comment by micskeiz** [comment]
This is a working example:
- https://github.com/micskeiz/Runin/tree/temp_travis

Analysis results on SonarCloud:
- https://sonarcloud.io/project/issues?branch=temp_travis&id=micskeiz_Runin&resolved=false

There are a couple of recommendations for the source code.

There is one problem: it counts `build` as a source folder and analyzes it also. This can be prevented by specifying `sonar.sources` and `sonar.tests` in the Sonar property file, but it needs separate src and test folder (see #43 ).

**Comment by gergopokol** [comment]
Solution by @micskeiz  has been merged to branch temp_travis, and a report has been generated:
https://sonarcloud.io/dashboard?branch=temp_travis&id=osrep_Runin

**Comment by pordaniel01** [comment]
This issue had been moved to another repository. See issue [#4](https://github.com/osrep/Runaphys/issues/4)
