### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runin#6]
Have to update documentation.

**Comment by gergopokol** [comment]
Links and essential errors need to be corrected. Branch https://github.com/osrep/Runin/tree/review-Runin-imas can be merged afterwords.

**Comment by olaszsoma** [comment]
The documentation of the released actors has to be added to the [github](https://wpcd-workflows.github.io/) project of WPCD. This might not be permanent. Decide whether to add documentation anyway.

**Comment by olaszsoma** [comment]
Software requirements specification updated. User documentation should be updated, and the issue can be closed.

**Comment by gergopokol** [comment]
Updated online documentation of runaway codes: 
1. Updated the general description and obsoleted detailed descriptions on TWiki (https://portal.eufus.eu/twiki/bin/view/Main/HCD-ElectronRun-awayPhysics) In future we will reference the OSREP page for documentation (https://github.com/osrep).
2. Corrected and amended the new documentation at the ETS (https://wpcd-workflows.github.io/ets.html) and Codes (https://wpcd-workflows.github.io/codes.html) chapters - but encountered permission problems during push.

**Comment by gergopokol** [comment]
Update merged.
