### ISSUE TITLE
Add submodule download to build.sh

### ISSUE THREAD

**Issue by olaszsoma** [osrep/Runin#67]
The Runaphys submodule should be updated when the build.sh is run. It should check if the submodule is checked out at a specific commit and if not, it should download it. A similar method has been implemented with [TCI](https://gitlab.com/users/sign_in), this feature should be handled similarly.

**Comment by olaszsoma** [comment]
The implemented solution does not work if Runin is checked out as an svn repo. The Gforge actor release uses svn repositories, so it is not compatible with the current implementation. This issue has been raised in a [Gforge tracker](https://gforge6.eufus.eu/gf/project/generalsupport/tracker/?action=TrackerItemEdit&tracker_item_id=1763).

**Comment by pordaniel01** [comment]
The issue has been solved.
