### ISSUE TITLE
Setting the Runaphys submodule

### ISSUE THREAD

**Issue by pordaniel01** [osrep/Runin#70]
Runaway Physics submodule should be updated to the latest tag.

**Comment by pordaniel01** [comment]
Runin doesn't compiles with Runaphys 2.0.0. We will release Runin with Runaphys 1.0.0

**Comment by gergopokol** [comment]
> Runin doesn't compile with Runaphys 2.0.0. We will release Runin with Runaphys 1.0.0
This applies for release 2.0.?

**Comment by pordaniel01** [comment]
This issue has been resolved in this [issue](https://github.com/osrep/Runin/issues/79).
